version: '3'

services:
  oncall-prometheus:
    image: prom/prometheus
    user: root
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - iris
    ports:
      - "9090:9090"
    
  oncall-web:
    build: .
    hostname: oncall
    labels:
      - prometheus-job=oncall-web-auto
    ports:
      - "8080-8081:8080"
      - "8090-8091:8090"
    deploy:
      replicas: 2     
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml
    networks:
      - iris
  
  oncall-mysql:
    hostname: oncall-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - iris

networks:
  iris:
    name: iris
