global:
  resolve_timeout: 5m
templates:
  - "/etc/alertmanager/alerts.tmpl"
route:
  receiver: webhook_receiver
  group_by: ["alertname", "severity"]
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 4h
  routes:
    - receiver: telegram_receiver
      matchers:
        - severity="critical"
    - receiver: telegram_receiver
      group_wait: 5s
      group_interval: 10s
      repeat_interval: 1h
      matchers:
        - severity="warning"
      active_time_intervals:
        - work_hour

time_intervals:
  - name: work_hour
    time_intervals:
      - times:
          - start_time: 09:00
            end_time: 17:00
        weekdays: ["monday:friday"]
        location: 'Europe/Moscow'

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ["alertname"]

receivers:
  - name: webhook_receiver
    webhook_configs:
      - url: https://webhook.site/7052599f-9bb7-4863-966f-0c7d82a13986
        send_resolved: false
  - name: telegram_receiver
    telegram_configs:
      - chat_id: -4068393056
        bot_token: 5930309571:AAFN21Nj2z-0wZY-1h2ob6-3FsvH4qRu8P0
        send_resolved: true
        message: '{{ template "telegram.lordvidex.message" . }}'
