global:
  scrape_interval: "10s"
  scrape_timeout: "10s"
  evaluation_interval: "1m"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "localhost:9090"
  # - job_name: "oncall"
  #   static_configs:
  #     - targets:
  #       - "oncall-web:8090"

  - job_name: "docker-containers"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock # You can also use http/https to connect to the Docker daemon.
    relabel_configs:
      # Only keep containers that have a `prometheus-job` label.
      - source_labels: [__meta_docker_container_label_prometheus_job]
        regex: .+
        action: keep
      # Use the task labels that are prefixed by `prometheus-`.
      - regex: __meta_docker_container_label_prometheus_(.+)
        action: labelmap
        replacement: $1
      # keep sources with port  8090
      - source_labels: [__meta_docker_port_private]
        regex: ^8090$
        action: keep
