global:
  scrape_interval: "10s"
  scrape_timeout: "10s"
  evaluation_interval: "1m"
rule_files:
  - rules.yml
alerting:
  alertmanagers:
    - static_configs:  
        - targets:
            - alertmanager:9093
scrape_configs:
  - job_name: "node"
    static_configs:
      - targets:
          - "node-exporter:9100"

  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "sla-prober"
    metrics_path: /probe
    static_configs:
      - targets:
          - "sla-prober:8091"

  - job_name: "docker-containers"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock # You can also use http/https to connect to the Docker daemon.
    relabel_configs:
      # Only keep containers that have a `prometheus-job` label.
      - source_labels: [__meta_docker_container_label_prometheus_job]
        regex: .+
        action: keep
      # Use the task labels that are prefixed by `prometheus-`.
      - regex: __meta_docker_container_label_prometheus_(.+)
        action: labelmap
        replacement: $1
      # keep sources with port  8090
      - source_labels: [__meta_docker_port_private]
        regex: ^8090$
        action: keep

  - job_name: "blackbox_http"
    scrape_interval: "30s"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - "oncall-web:8080"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
  - job_name: "blackbox_tcp"
    scrape_interval: "30s"
    metrics_path: /probe
    params:
      module: [tcp]
    static_configs:
      - targets:
          - "oncall-web:8080"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
  - job_name: "blackbox_icmp"
    scrape_interval: "30s"
    metrics_path: /probe
    params:
      module: [icmp_ipv4]
    static_configs:
      - targets:
          - "oncall-web"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
