global:
  scrape_interval: "1m"
  scrape_timeout: "10s"
  evaluation_interval: "1m"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "localhost:9090"
  - job_name: "oncall"
    static_configs:
      - targets:
        - "oncall-web:8090"
