groups:
  - name: BlackBox Probe Alerts 
    rules:
      - alert: BlackBoxExporterDown
        expr: up{job=~"blackbox.*"} == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: BlackBox Exporter Down (job {{ $labels.job }})
          description: "Node Exporter is down\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: BlackboxProbeFailed
        expr: probe_success == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Blackbox probe failed (instance {{ $labels.instance }})
          description: "Probe failed\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: BlackboxSlowProbe
        expr: avg_over_time(probe_duration_seconds[1m]) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Blackbox slow probe (instance {{ $labels.instance }})
          description: "Blackbox probe took more than 1s to complete\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: BlackboxProbeSlowHttp
        expr: avg_over_time(probe_http_duration_seconds[1m]) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Blackbox probe slow HTTP (instance {{ $labels.instance }})
          description: "HTTP request took more than 1s\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: BlackboxProbeHttpFailure
        expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Blackbox probe HTTP failure (instance {{ $labels.instance }})
          description: "HTTP status code is not 200-399\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  - name: NodeExporter Alerts
    rules:
      - alert: NodeExporterDown
        expr: up{job="node"} == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Node Exporter Down (instance {{ $labels.instance }})
          description: "Node Exporter is down\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: NodeHighCpuLoad
        expr: (sum by (instance) (avg by (mode, instance) (rate(node_cpu_seconds_total{mode!="idle"}[2m]))) > 0.8) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Host high CPU load (instance {{ $labels.instance }})
          description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  - name: OncallExporter Alerts
    rules:
      - alert: NotificationsFailing
        expr: increase(oncallnotifier_message_fail_cnt[1m]) > 0
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: Notifications failing (instance {{ $labels.instance }})
          description: "Rate of change of failing notifications has been greater than zero for 30s\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
